site:
  name: Pleasant Home
  subname: Community Church
  address: 32120 SE Dodge Park Blvd
  cityState: Gresham, OR 97080
  appleMaps: "https://maps.apple.com/?address=32120%20SE%20Dodge%20Park%20Blvd,%20Gresham,%20OR%20%2097080,%20United%20States&auid=13413920591760178387&ll=45.469195,-122.332160&lsp=9902&q=Pleasant%20Home%20Community%20Church&t=m"
  googleMaps: "https://maps.app.goo.gl/iDan1NWYLZNPYE6h7"
  phone: (503) 663-3668
  site: 'https://www.pleasanthome.cc'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: null

# Default SEO metadata
metadata:
  title:
    default: Pleasant Home Community Church
    template: '%s — Pleasant Home Community Church'
  description: "Pleasant Home Community Church was established in 1897. It has a long history of biblical faithfulness which has continued today through the expository preaching of God's Word"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Pleasant Home Community Church
    images:
      - url: '~/assets/images/phcc-front-building.webp'
        width: 1200
        height: 628
    type: website
  # twitter:
  #   handle: '@onwidget'
  #   site: '@onwidget'
  #   cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  ministries:
    isEnabled: true
    postsPerPage: 6

    ministries:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'ministries' # Ministries main path, you can change this to "articles" (/articles)
      robots:
        index: true

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
